apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-jenkins-operator
  namespace: jenkins-operator-system
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: openshift-jenkins-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
