apiVersion: builtin
kind: LabelTransformer
metadata:
  name: k8s-labels
labels:
  app.kubernetes.io/component: 3scale-gateway-stage
  app.kubernetes.io/instance: 3scale-gateway-stage
fieldSpecs:
- path: metadata/labels
  create: true