apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

bases:
- ../aggregate

resources:
- namespace.yaml

patchesJson6902:
- target:
    version: v1
    group: operators.coreos.com
    kind: OperatorGroup
    name: grafana
  path: patch-operator-group.yaml
- target:
    version: v1
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: grafana-proxy
  path: patch-proxy-namespace.yaml