apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: codeready-workspaces
  namespace: openshift-workspaces
spec:
  channel: "4.6"
  installPlanApproval: Automatic
  name: codeready-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
