kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-compliance

resources:
  - github.com/85matthew/catalog/compliance-operator/base
  - namespace.yaml
  - operator-group.yaml

patchesJson6902:
  - path: patch-channel-csv.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: compliance-operator
      version: v1alpha1
