apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jenkins-cm.yaml
- jenkins-dc.yaml
- jenkins-jnlp.yaml
- jenkins-pvc.yaml
- jenkins-rolebinding.yaml
- jenkins-route.yaml
- jenkins-sa.yaml
- jenkins-svc.yaml
- maven-m2-pvc.yaml
- maven-settings-cm.yaml
- nexus-secret.yaml
