apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.io/sonatype/nexus:2.14.18
    importPolicy: {}
    name: 2.14.18
    referencePolicy:
      type: Source
