apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- ../../base/operator
- ../../base/instance
- grafana-ds.yaml
- patch-grafana-ds-sa.yaml
- patch-grafana-ds-job.yaml
- cluster-monitor-view-rb.yaml